---

- name: Blockinfile to edit files
  gather_facts: false
  hosts: backup2
  tasks:
    - name: "Adding Ansible manager and managed nodes to /etc/hosts"
      blockinfile:
        name: /home/ubuntu
        block: | 
          # Manager
          10.73.199.13 manager

        marker: "# {mark} ANSIBLE MANAGED BLOCK manager and managed nodes" 