
---
# file: vms.yml
- hosts: storage
  tasks:

# Tests
- name: Basic playbook run locally 
  gather_facts: true 
  hosts: all
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"

# Initial Backup Setup
    - name: Initial volume configuration # initial storage volume config
      become: true
      tags: [ 'initial-backup-config' ]
      block:
        - name: Volume Group Create on top of disks # create pv and vg
          community.general.lvg:
            vg: vg.services
            pvs: /dev/sdb
            #pesize: 32
            #pvs: "{{ vg_devices }}" # pvcreate
            #vg: "{{ vg_name }}" # vgcreate

        #- name: Logical Volume Create of given size # Create lv
         # community.general.lvol:
          #  vg: vg.services
           # lv: -L 100M -n data test
            #size: 40K